services:
  backend:
    volumes:
      - ./backend:/app
    build: ./backend
    ports:
      - "8080:8000"
  frontend:
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/static:/app/static
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend