services:
  backend:
    volumes:
      - ./backend:/app
    build: ./backend
    ports:
      - "8000:8000"
  frontend:
    volumes:
      - ./frontend:/app
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend